--tipo de catalogo de departamentos
INSERT INTO votaciones.TipoCatalogo (idTipoCatalogo, descripcion, fechaAdicion) VALUES (1, 'Departamento', CURRENT_TIMESTAMP);

--tipo de catalogo de municipios
INSERT INTO votaciones.TipoCatalogo (idTipoCatalogo, descripcion, fechaAdicion) VALUES (2, 'Municipios', CURRENT_TIMESTAMP);

--tipo de catalogo de municipios
INSERT INTO votaciones.TipoCatalogo (idTipoCatalogo, descripcion, fechaAdicion) VALUES (3, 'Tipo Candidatos', CURRENT_TIMESTAMP);

--tipo de catalogo de partidos politicos
INSERT INTO votaciones.TipoCatalogo (idTipoCatalogo, descripcion, fechaAdicion) VALUES (4, 'Partidos Politicos', CURRENT_TIMESTAMP);


--tipo de catalogo de los candidatos
INSERT INTO votaciones.TipoCatalogo (idTipoCatalogo, descripcion, fechaAdicion) VALUES (5, 'Candidatos', CURRENT_TIMESTAMP);


--insert de los catalogos
-- Inserts para Departamentos
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion)
VALUES
  (1, 1, 'AV', 'Alta Verapaz', CURRENT_TIMESTAMP), 
  (2, 1, 'BV', 'Baja Verapaz', CURRENT_TIMESTAMP), 
  (3, 1, 'CM', 'Chimaltenango', CURRENT_TIMESTAMP), 
  (4, 1, 'CQ', 'Chiquimula', CURRENT_TIMESTAMP), 
  (5, 1, 'PE', 'Petén', CURRENT_TIMESTAMP), 
  (6, 1, 'IZ', 'Izabal', CURRENT_TIMESTAMP), 
  (7, 1, 'ZA', 'Zacapa', CURRENT_TIMESTAMP), 
  (8, 1, 'JA', 'Jalapa', CURRENT_TIMESTAMP), 
  (9, 1, 'JU', 'Jutiapa', CURRENT_TIMESTAMP), 
  (10, 1, 'SR', 'Santa Rosa', CURRENT_TIMESTAMP), 
  (11, 1, 'SO', 'Sololá', CURRENT_TIMESTAMP), 
  (12, 1, 'SU', 'Suchitepéquez', CURRENT_TIMESTAMP), 
  (13, 1, 'RE', 'Retalhuleu', CURRENT_TIMESTAMP), 
  (14, 1, 'SF', 'San Marcos', CURRENT_TIMESTAMP), 
  (15, 1, 'HU', 'Huehuetenango', CURRENT_TIMESTAMP), 
  (16, 1, 'QU', 'Quiché', CURRENT_TIMESTAMP), 
  (17, 1, 'ES', 'Escuintla', CURRENT_TIMESTAMP), 
  (18, 1, 'GU', 'Guatemala', CURRENT_TIMESTAMP), 
  (19, 1, 'MS', 'Sacatepequez', CURRENT_TIMESTAMP),
  (20, 1, 'TQ', 'Totonicapán', CURRENT_TIMESTAMP), 
  (21, 1, 'EP', 'El progreso', CURRENT_TIMESTAMP),
  (22, 1, 'QZ', 'Quetzaltenango', CURRENT_TIMESTAMP);



-- Inserts para Municipios de Alta Verapaz
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (23, 2, 'SALAMA', 'SALAMA', CURRENT_TIMESTAMP, 1),
  (24, 2, 'SAN MIGUEL CHICAJ', 'SAN MIGUEL CHICAJ', CURRENT_TIMESTAMP, 1),
  (25, 2, 'RABINAL', 'RABINAL', CURRENT_TIMESTAMP, 1),
  (26, 2, 'CUBULCO', 'CUBULCO', CURRENT_TIMESTAMP, 1),
  (27, 2, 'GRANADOS', 'GRANADOS', CURRENT_TIMESTAMP, 1),
  (28, 2, 'SANTA CRUZ EL CHOL', 'SANTA CRUZ EL CHOL', CURRENT_TIMESTAMP, 1),
  (29, 2, 'SAN JERONIMO', 'SAN JERONIMO', CURRENT_TIMESTAMP, 1),
  (30, 2, 'PURULHA', 'PURULHA', CURRENT_TIMESTAMP, 1);

-- Inserts para Municipios de Baja Verapaz
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (31, 2, 'COBAN', 'COBAN', CURRENT_TIMESTAMP, 2),
  (32, 2, 'SANTA CRUZ VERAPAZ', 'SANTA CRUZ VERAPAZ', CURRENT_TIMESTAMP, 2),
  (33, 2, 'SAN CRISTOBAL VERAPAZ', 'SAN CRISTOBAL VERAPAZ', CURRENT_TIMESTAMP, 2),
  (34, 2, 'TACTIC', 'TACTIC', CURRENT_TIMESTAMP, 2),
  (35, 2, 'TAMAHU', 'TAMAHU', CURRENT_TIMESTAMP, 2),
  (36, 2, 'SAN MIGUEL TUCURU', 'SAN MIGUEL TUCURU', CURRENT_TIMESTAMP, 2),
  (37, 2, 'PANZOS', 'PANZOS', CURRENT_TIMESTAMP, 2),
  (38, 2, 'SENAHU', 'SENAHU', CURRENT_TIMESTAMP, 2),
  (39, 2, 'SAN PEDRO CARCHA', 'SAN PEDRO CARCHA', CURRENT_TIMESTAMP, 2),
  (40, 2, 'SAN JUAN CHAMELCO', 'SAN JUAN CHAMELCO', CURRENT_TIMESTAMP, 2),
  (41, 2, 'LANQUIN', 'LANQUIN', CURRENT_TIMESTAMP, 2),
  (42, 2, 'SANTA MARIA CAHABON', 'SANTA MARIA CAHABON', CURRENT_TIMESTAMP, 2),
  (43, 2, 'CHISEC', 'CHISEC', CURRENT_TIMESTAMP, 2),
  (44, 2, 'CHAHAL', 'CHAHAL', CURRENT_TIMESTAMP, 2),
  (45, 2, 'FRAY BARTOLOME DE LAS CASAS', 'FRAY BARTOLOME DE LAS CASAS', CURRENT_TIMESTAMP, 2),
  (46, 2, 'LA TINTA', 'LA TINTA', CURRENT_TIMESTAMP, 2),
  (47, 2, 'RAXRUHA', 'RAXRUHA', CURRENT_TIMESTAMP, 2);

-- Inserts para Municipios de Chimaltenango
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (48, 2, 'CHIMALTENANGO', 'CHIMALTENANGO', CURRENT_TIMESTAMP, 3),
  (49, 2, 'SAN JOSE POAQUIL', 'SAN JOSE POAQUIL', CURRENT_TIMESTAMP, 3),
  (50, 2, 'SAN MARTIN JILOTEPEQUE', 'SAN MARTIN JILOTEPEQUE', CURRENT_TIMESTAMP, 3),
  (51, 2, 'SAN JUAN COMALAPA', 'SAN JUAN COMALAPA', CURRENT_TIMESTAMP, 3),
  (52, 2, 'SANTA APOLONIA', 'SANTA APOLONIA', CURRENT_TIMESTAMP, 3),
  (53, 2, 'TECPAN GUATEMALA', 'TECPAN GUATEMALA', CURRENT_TIMESTAMP, 3),
  (54, 2, 'PATZUN', 'PATZUN', CURRENT_TIMESTAMP, 3),
  (55, 2, 'SAN MIGUEL POCHUTA', 'SAN MIGUEL POCHUTA', CURRENT_TIMESTAMP, 3),
  (56, 2, 'PATZICIA', 'PATZICIA', CURRENT_TIMESTAMP, 3),
  (57, 2, 'SANTA CRUZ BALANYA', 'SANTA CRUZ BALANYA', CURRENT_TIMESTAMP, 3),
  (58, 2, 'ACATENANGO', 'ACATENANGO', CURRENT_TIMESTAMP, 3),
  (59, 2, 'SAN PEDRO YEPOCAPA', 'SAN PEDRO YEPOCAPA', CURRENT_TIMESTAMP, 3),
  (60, 2, 'SAN ANDRES ITZAPA', 'SAN ANDRES ITZAPA', CURRENT_TIMESTAMP, 3),
  (61, 2, 'PARRAMOS', 'PARRAMOS', CURRENT_TIMESTAMP, 3),
  (62, 2, 'ZARAGOZA', 'ZARAGOZA', CURRENT_TIMESTAMP, 3),
  (63, 2, 'EL TEJAR', 'EL TEJAR', CURRENT_TIMESTAMP, 3);

-- Municipios de Chiquimula
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (64, 2, 'CHI', 'CHIQUIMULA', CURRENT_TIMESTAMP, 4),
  (65, 2, 'SJA', 'SAN JOSE LA ARADA', CURRENT_TIMESTAMP, 4),
  (66, 2, 'SJE', 'SAN JUAN LA ERMITA', CURRENT_TIMESTAMP, 4),
  (67, 2, 'JOC', 'JOCOTAN', CURRENT_TIMESTAMP, 4),
  (68, 2, 'CAM', 'CAMOTAN', CURRENT_TIMESTAMP, 4),
  (69, 2, 'OLO', 'OLOPA', CURRENT_TIMESTAMP, 4),
  (70, 2, 'ESQ', 'ESQUIPULAS', CURRENT_TIMESTAMP, 4),
  (71, 2, 'CON', 'CONCEPCION LAS MINAS', CURRENT_TIMESTAMP, 4),
  (72, 2, 'QUE', 'QUEZALTEPEQUE', CURRENT_TIMESTAMP, 4),
  (73, 2, 'SJT', 'SAN JACINTO', CURRENT_TIMESTAMP, 4),
  (74, 2, 'IPA', 'IPALA', CURRENT_TIMESTAMP, 4);

-- Municipios de Petén
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (75, 2, 'FLO', 'FLORES', CURRENT_TIMESTAMP, 5),
  (76, 2, 'SJO', 'SAN JOSE', CURRENT_TIMESTAMP, 5),
  (77, 2, 'SBE', 'SAN BENITO', CURRENT_TIMESTAMP, 5),
  (78, 2, 'SAD', 'SAN ANDRES', CURRENT_TIMESTAMP, 5),
  (79, 2, 'LLB', 'LA LIBERTAD', CURRENT_TIMESTAMP, 5),
  (80, 2, 'SFR', 'SAN FRANCISCO', CURRENT_TIMESTAMP, 5),
  (81, 2, 'SNA', 'SANTA ANA', CURRENT_TIMESTAMP, 5),
  (82, 2, 'DOL', 'DOLORES', CURRENT_TIMESTAMP, 5),
  (83, 2, 'SLU', 'SAN LUIS', CURRENT_TIMESTAMP, 5),
  (84, 2, 'SAY', 'SAYAXCHE', CURRENT_TIMESTAMP, 5),
  (85, 2, 'MMM', 'MELCHOR DE MENCOS', CURRENT_TIMESTAMP, 5),
  (86, 2, 'POP', 'POPTUN', CURRENT_TIMESTAMP, 5);

-- Municipios de Izabal
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (87, 2, 'PUB', 'PUERTO BARRIOS', CURRENT_TIMESTAMP, 6),
  (88, 2, 'LIV', 'LIVINGSTON', CURRENT_TIMESTAMP, 6),
  (89, 2, 'EST', 'EL ESTOR', CURRENT_TIMESTAMP, 6),
  (90, 2, 'MOR', 'MORALES', CURRENT_TIMESTAMP, 6),
  (91, 2, 'AMA', 'LOS AMATES', CURRENT_TIMESTAMP, 6);

-- Municipios de Zacapa
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (92, 2, 'ZAC', 'ZACAPA', CURRENT_TIMESTAMP, 7),
  (93, 2, 'EST', 'ESTANZUELA', CURRENT_TIMESTAMP, 7),
  (94, 2, 'RIO', 'RIO HONDO', CURRENT_TIMESTAMP, 7),
  (95, 2, 'GUA', 'GUALAN', CURRENT_TIMESTAMP, 7),
  (96, 2, 'TEC', 'TECULUTAN', CURRENT_TIMESTAMP, 7),
  (97, 2, 'USU', 'USUMATLAN', CURRENT_TIMESTAMP, 7),
  (98, 2, 'CAB', 'CABANAS', CURRENT_TIMESTAMP, 7),
  (99, 2, 'SDI', 'SAN DIEGO', CURRENT_TIMESTAMP, 7),
  (100, 2, 'LUN', 'LA UNION', CURRENT_TIMESTAMP, 7),
  (101, 2, 'HUI', 'HUITE', CURRENT_TIMESTAMP, 7);

-- Municipios de Jalapa
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (102, 2, 'JAL', 'JALAPA', CURRENT_TIMESTAMP, 8),
  (103, 2, 'SPP', 'SAN PEDRO PINULA', CURRENT_TIMESTAMP, 8),
  (104, 2, 'SLJ', 'SAN LUIS JILOTEPEQUE', CURRENT_TIMESTAMP, 8),
  (105, 2, 'SMC', 'SAN MANUEL CHAPARRON', CURRENT_TIMESTAMP, 8),
  (106, 2, 'SCA', 'SAN CARLOS ALZATATE', CURRENT_TIMESTAMP, 8),
  (107, 2, 'MON', 'MONJAS', CURRENT_TIMESTAMP, 8),
  (108, 2, 'MAT', 'MATAQUESCUINTLA', CURRENT_TIMESTAMP, 8);

-- Municipios de Jutiapa
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (109, 2, 'JUT', 'JUTIAPA', CURRENT_TIMESTAMP, 9),
  (110, 2, 'EPR', 'EL PROGRESO', CURRENT_TIMESTAMP, 9),
  (111, 2, 'SCM', 'SANTA CATARINA MITA', CURRENT_TIMESTAMP, 9),
  (112, 2, 'ABL', 'AGUA BLANCA', CURRENT_TIMESTAMP, 9),
  (113, 2, 'ASM', 'ASUNCION MITA', CURRENT_TIMESTAMP, 9),
  (114, 2, 'YUP', 'YUPILTEPEQUE', CURRENT_TIMESTAMP, 9),
  (115, 2, 'ATE', 'ATESCATEMPA', CURRENT_TIMESTAMP, 9),
  (116, 2, 'JER', 'JEREZ', CURRENT_TIMESTAMP, 9),
  (117, 2, 'EAD', 'EL ADELANTO', CURRENT_TIMESTAMP, 9),
  (118, 2, 'ZAP', 'ZAPOTITLAN', CURRENT_TIMESTAMP, 9),
  (119, 2, 'COM', 'COMAPA', CURRENT_TIMESTAMP, 9),
  (120, 2, 'JAL', 'JALPATAGUA', CURRENT_TIMESTAMP, 9),
  (121, 2, 'CON', 'CONGUACO', CURRENT_TIMESTAMP, 9),
  (122, 2, 'MOY', 'MOYUTA', CURRENT_TIMESTAMP, 9),
  (123, 2, 'PAS', 'PASACO', CURRENT_TIMESTAMP, 9),
  (124, 2, 'SJA', 'SAN JOSE ACATEMPA', CURRENT_TIMESTAMP, 9),
  (125, 2, 'QUE', 'QUESADA', CURRENT_TIMESTAMP, 9);

-- Municipios de Santa Rosa
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (126, 2, 'CUI', 'CUILAPA', CURRENT_TIMESTAMP, 10),
  (127, 2, 'BAR', 'BARBERENA', CURRENT_TIMESTAMP, 10),
  (128, 2, 'SRL', 'SANTA ROSA DE LIMA', CURRENT_TIMESTAMP, 10),
  (129, 2, 'CAS', 'CASILLAS', CURRENT_TIMESTAMP, 10),
  (130, 2, 'SRL', 'SAN RAFAEL LAS FLORES', CURRENT_TIMESTAMP, 10),
  (131, 2, 'ORA', 'ORATORIO', CURRENT_TIMESTAMP, 10),
  (132, 2, 'SJT', 'SAN JUAN TECUACO', CURRENT_TIMESTAMP, 10),
  (133, 2, 'CHI', 'CHIQUIMULILLA', CURRENT_TIMESTAMP, 10),
  (134, 2, 'TAX', 'TAXISCO', CURRENT_TIMESTAMP, 10),
  (135, 2, 'SMI', 'SANTA MARIA IXHUATAN', CURRENT_TIMESTAMP, 10),
  (136, 2, 'GUA', 'GUAZACAPAN', CURRENT_TIMESTAMP, 10),
  (137, 2, 'SCR', 'SANTA CRUZ NARANJO', CURRENT_TIMESTAMP, 10),
  (138, 2, 'PNU', 'PUEBLO NUEVO VIÑAS', CURRENT_TIMESTAMP, 10),
  (139, 2, 'NSR', 'NUEVA SANTA ROSA', CURRENT_TIMESTAMP, 10);

-- Municipios de Sololá
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (140, 2, 'SOL', 'SOLOLA', CURRENT_TIMESTAMP, 11),
  (141, 2, 'SJC', 'SAN JOSE CHACAYA', CURRENT_TIMESTAMP, 11),
  (142, 2, 'SMV', 'SANTA MARIA VISITACION', CURRENT_TIMESTAMP, 11),
  (143, 2, 'SLU', 'SANTA LUCIA UTATLAN', CURRENT_TIMESTAMP, 11),
  (144, 2, 'NAH', 'NAHUALA', CURRENT_TIMESTAMP, 11),
  (145, 2, 'SCI', 'SANTA CATARINA IXTAHUACAN', CURRENT_TIMESTAMP, 11),
  (146, 2, 'SCL', 'SANTA CLARA LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (147, 2, 'CON', 'CONCEPCION', CURRENT_TIMESTAMP, 11),
  (148, 2, 'SES', 'SAN ANDRES SEMETABAJ', CURRENT_TIMESTAMP, 11),
  (149, 2, 'PAN', 'PANAJACHEL', CURRENT_TIMESTAMP, 11),
  (150, 2, 'SCP', 'SANTA CATARINA PALOPO', CURRENT_TIMESTAMP, 11),
  (151, 2, 'SAP', 'SAN ANTONIO PALOPO', CURRENT_TIMESTAMP, 11),
  (152, 2, 'SLT', 'SAN LUCAS TOLIMAN', CURRENT_TIMESTAMP, 11),
  (153, 2, 'SCL', 'SANTA CRUZ LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (154, 2, 'SPL', 'SAN PABLO LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (155, 2, 'SMC', 'SAN MARCOS LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (156, 2, 'SJL', 'SAN JUAN LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (157, 2, 'SPL', 'SAN PEDRO LA LAGUNA', CURRENT_TIMESTAMP, 11),
  (158, 2, 'SAT', 'SANTIAGO ATITLAN', CURRENT_TIMESTAMP, 11);

-- Municipios de Suchitepéquez
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (159, 2, 'MAZ', 'MAZATENANGO', CURRENT_TIMESTAMP, 12),
  (160, 2, 'CUY', 'CUYOTENANGO', CURRENT_TIMESTAMP, 12),
  (161, 2, 'SFZ', 'SAN FRANCISCO ZAPOTITLAN', CURRENT_TIMESTAMP, 12),
  (162, 2, 'SBE', 'SAN BERNARDINO', CURRENT_TIMESTAMP, 12),
  (163, 2, 'SJI', 'SAN JOSE EL IDOLO', CURRENT_TIMESTAMP, 12),
  (164, 2, 'SDS', 'SANTO DOMINGO SUCHITEPEQUEZ', CURRENT_TIMESTAMP, 12),
  (165, 2, 'SLO', 'SAN LORENZO', CURRENT_TIMESTAMP, 12),
  (166, 2, 'SAM', 'SAMAYAC', CURRENT_TIMESTAMP, 12),
  (167, 2, 'SPJ', 'SAN PABLO JOCOPILAS', CURRENT_TIMESTAMP, 12),
  (168, 2, 'SAS', 'SAN ANTONIO SUCHITEPEQUEZ', CURRENT_TIMESTAMP, 12),
  (169, 2, 'SMP', 'SAN MIGUEL PANAM', CURRENT_TIMESTAMP, 12),
  (170, 2, 'SGA', 'SAN GABRIEL', CURRENT_TIMESTAMP, 12),
  (171, 2, 'CHC', 'CHICACAO', CURRENT_TIMESTAMP, 12),
  (172, 2, 'PAT', 'PATULUL', CURRENT_TIMESTAMP, 12),
  (173, 2, 'SBA', 'SANTA BARBARA', CURRENT_TIMESTAMP, 12),
  (174, 2, 'SJB', 'SAN JUAN BAUTISTA', CURRENT_TIMESTAMP, 12),
  (175, 2, 'STU', 'SANTO TOMAS LA UNION', CURRENT_TIMESTAMP, 12),
  (176, 2, 'ZUN', 'ZUNILITO', CURRENT_TIMESTAMP, 12),
  (177, 2, 'PNU', 'PUEBLO NUEVO', CURRENT_TIMESTAMP, 12),
  (178, 2, 'RBR', 'RIO BRAVO', CURRENT_TIMESTAMP, 12);


-- Municipios de Retalhuleu
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (179, 2, 'RET', 'RETALHULEU', CURRENT_TIMESTAMP, 13),
  (180, 2, 'SSE', 'SAN SEBASTIAN', CURRENT_TIMESTAMP, 13),
  (181, 2, 'SCM', 'SANTA CRUZ MULUA', CURRENT_TIMESTAMP, 13),
  (182, 2, 'SMZ', 'SAN MARTIN ZAPOTITLAN', CURRENT_TIMESTAMP, 13),
  (183, 2, 'SFE', 'SAN FELIPE', CURRENT_TIMESTAMP, 13),
  (184, 2, 'SAV', 'SAN ANDRES VILLA SECA', CURRENT_TIMESTAMP, 13),
  (185, 2, 'CHA', 'CHAMPERICO', CURRENT_TIMESTAMP, 13),
  (186, 2, 'NSC', 'NUEVO SAN CARLOS', CURRENT_TIMESTAMP, 13),
  (187, 2, 'EAS', 'EL ASINTAL', CURRENT_TIMESTAMP, 13);

-- Municipios de San Marcos
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (188, 2, 'SMA', 'SAN MARCOS', CURRENT_TIMESTAMP, 14),
  (189, 2, 'SPS', 'SAN PEDRO SACATEPEQUEZ', CURRENT_TIMESTAMP, 14),
  (190, 2, 'SAS', 'SAN ANTONIO SACATEPEQUEZ', CURRENT_TIMESTAMP, 14),
  (191, 2, 'COM', 'COMITANCILLO', CURRENT_TIMESTAMP, 14),
  (192, 2, 'SMI', 'SAN MIGUEL IXTAHUACAN', CURRENT_TIMESTAMP, 14),
  (193, 2, 'COT', 'CONCEPCION TUTUAPA', CURRENT_TIMESTAMP, 14),
  (194, 2, 'TAC', 'TACANA', CURRENT_TIMESTAMP, 14),
  (195, 2, 'SIB', 'SIBINAL', CURRENT_TIMESTAMP, 14),
  (196, 2, 'TAJ', 'TAJUMULCO', CURRENT_TIMESTAMP, 14),
  (197, 2, 'TEJ', 'TEJUTLA', CURRENT_TIMESTAMP, 14),
  (198, 2, 'SRP', 'SAN RAFAEL PIE DE LA CUESTA', CURRENT_TIMESTAMP, 14),
  (199, 2, 'NPR', 'NUEVO PROGRESO', CURRENT_TIMESTAMP, 14),
  (200, 2, 'TUM', 'EL TUMBADOR', CURRENT_TIMESTAMP, 14),
  (201, 2, 'SJR', 'SAN JOSE EL RODEO', CURRENT_TIMESTAMP, 14),
  (202, 2, 'MAL', 'MALACATAN', CURRENT_TIMESTAMP, 14),
  (203, 2, 'CAT', 'CATARINA', CURRENT_TIMESTAMP, 14),
  (204, 2, 'AYU', 'AYUTLA (TECUN UMAN)', CURRENT_TIMESTAMP, 14),
  (205, 2, 'OCO', 'OCOS', CURRENT_TIMESTAMP, 14),
  (206, 2, 'SPB', 'SAN PABLO', CURRENT_TIMESTAMP, 14),
  (207, 2, 'QUE', 'EL QUETZAL', CURRENT_TIMESTAMP, 14),
  (208, 2, 'LAR', 'LA REFORMA', CURRENT_TIMESTAMP, 14),
  (209, 2, 'PAJ', 'PAJAPITA', CURRENT_TIMESTAMP, 14),
  (210, 2, 'IXC', 'IXCHIGUAN', CURRENT_TIMESTAMP, 14),
  (211, 2, 'SJO', 'SAN JOSE OJETENAN', CURRENT_TIMESTAMP, 14),
  (212, 2, 'SCC', 'SAN CRISTOBAL CUCHO', CURRENT_TIMESTAMP, 14),
  (213, 2, 'SIP', 'SIPACAPA', CURRENT_TIMESTAMP, 14),
  (214, 2, 'ESQ', 'ESQUIPULAS PALO GORDO', CURRENT_TIMESTAMP, 14),
  (215, 2, 'RIO', 'RIO BLANCO', CURRENT_TIMESTAMP, 14),
  (216, 2, 'SLZ', 'SAN LORENZO', CURRENT_TIMESTAMP, 14);

-- Municipios de Huehuetenango
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (217, 2, 'HUE', 'HUEHUETENANGO', CURRENT_TIMESTAMP, 15),
  (218, 2, 'CHI', 'CHIANTLA', CURRENT_TIMESTAMP, 15),
  (219, 2, 'MAL', 'MALACATANCITO', CURRENT_TIMESTAMP, 15),
  (220, 2, 'CUI', 'CUILCO', CURRENT_TIMESTAMP, 15),
  (221, 2, 'NEN', 'NENTON', CURRENT_TIMESTAMP, 15),
  (222, 2, 'SPN', 'SAN PEDRO NECTA', CURRENT_TIMESTAMP, 15),
  (223, 2, 'JAC', 'JACALTENANGO', CURRENT_TIMESTAMP, 15),
  (224, 2, 'SPS', 'SAN PEDRO SOLOMA', CURRENT_TIMESTAMP, 15),
  (225, 2, 'SII', 'SAN ILDEFONSO IXTAHUACAN', CURRENT_TIMESTAMP, 15),
  (226, 2, 'SBA', 'SANTA BARBARA', CURRENT_TIMESTAMP, 15),
  (227, 2, 'LLB', 'LA LIBERTAD', CURRENT_TIMESTAMP, 15),
  (228, 2, 'LDE', 'LA DEMOCRACIA', CURRENT_TIMESTAMP, 15),
  (229, 2, 'SMA', 'SAN MIGUEL ACATAN', CURRENT_TIMESTAMP, 15),
  (230, 2, 'SRI', 'SAN RAFAEL LA INDEPENDENCIA', CURRENT_TIMESTAMP, 15),
  (231, 2, 'TSC', 'TODOS SANTOS CUCHUMATAN', CURRENT_TIMESTAMP, 15),
  (232, 2, 'SJA', 'SAN JUAN ATITAN', CURRENT_TIMESTAMP, 15),
  (233, 2, 'SEU', 'SANTA EULALIA', CURRENT_TIMESTAMP, 15),
  (234, 2, 'SMI', 'SAN MATEO IXTATAN', CURRENT_TIMESTAMP, 15),
  (235, 2, 'COL', 'COLOTENANGO', CURRENT_TIMESTAMP, 15),
  (236, 2, 'SSH', 'SAN SEBASTIAN HUEHUETENANGO', CURRENT_TIMESTAMP, 15),
  (237, 2, 'TEC', 'TECTITAN', CURRENT_TIMESTAMP, 15),
  (238, 2, 'CON', 'CONCEPCION HUISTA', CURRENT_TIMESTAMP, 15),
  (239, 2, 'SJI', 'SAN JUAN IXCOY', CURRENT_TIMESTAMP, 15),
  (240, 2, 'SAH', 'SAN ANTONIO HUISTA', CURRENT_TIMESTAMP, 15),
  (241, 2, 'SSC', 'SAN SEBASTIAN COATAN', CURRENT_TIMESTAMP, 15),
  (242, 2, 'SCB', 'SANTA CRUZ BARILLAS', CURRENT_TIMESTAMP, 15),
  (243, 2, 'AGU', 'AGUACATAN', CURRENT_TIMESTAMP, 15),
  (244, 2, 'SRP', 'SAN RAFAEL PETZAL', CURRENT_TIMESTAMP, 15),
  (245, 2, 'SGI', 'SAN GASPAR IXCHIL', CURRENT_TIMESTAMP, 15),
  (246, 2, 'SCH', 'SANTIAGO CHIMALTENANGO', CURRENT_TIMESTAMP, 15),
  (247, 2, 'SAH', 'SANTA ANA HUISTA', CURRENT_TIMESTAMP, 15),
  (248, 2, 'UCN', 'UNION CANTINIL', CURRENT_TIMESTAMP, 15);

-- Municipios de Quiché
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (249, 2, 'SCQ', 'SANTA CRUZ DEL QUICHE', CURRENT_TIMESTAMP, 16),
  (250, 2, 'CHI', 'CHICHE', CURRENT_TIMESTAMP, 16),
  (251, 2, 'CHQ', 'CHINIQUE', CURRENT_TIMESTAMP, 16),
  (252, 2, 'ZAC', 'ZACUALPA', CURRENT_TIMESTAMP, 16),
  (253, 2, 'CHA', 'CHAJUL', CURRENT_TIMESTAMP, 16),
  (254, 2, 'STC', 'STO TOMAS CHICHICASTENANGO', CURRENT_TIMESTAMP, 16),
  (255, 2, 'PAT', 'PATZITE', CURRENT_TIMESTAMP, 16),
  (256, 2, 'SAI', 'SAN ANTONIO ILOTENANGO', CURRENT_TIMESTAMP, 16),
  (257, 2, 'SPJ', 'SAN PEDRO JOCOPILAS', CURRENT_TIMESTAMP, 16),
  (258, 2, 'CUN', 'CUNEN', CURRENT_TIMESTAMP, 16),
  (259, 2, 'SJC', 'SAN JUAN COTZAL', CURRENT_TIMESTAMP, 16),
  (260, 2, 'JOY', 'JOYABAJ', CURRENT_TIMESTAMP, 16),
  (261, 2, 'NEB', 'NEBAJ', CURRENT_TIMESTAMP, 16),
  (262, 2, 'SAS', 'SAN ANDRES SAJCABAJA', CURRENT_TIMESTAMP, 16),
  (263, 2, 'SMU', 'SAN MIGUEL USPANTAN', CURRENT_TIMESTAMP, 16),
  (264, 2, 'SAC', 'SACAPULAS', CURRENT_TIMESTAMP, 16),
  (265, 2, 'SBJ', 'SAN BARTOLOME JOCOTENANGO', CURRENT_TIMESTAMP, 16),
  (266, 2, 'CAN', 'CANILLA', CURRENT_TIMESTAMP, 16),
  (267, 2, 'CHC', 'CHICAMAN', CURRENT_TIMESTAMP, 16),
  (268, 2, 'IXC', 'IXCAN', CURRENT_TIMESTAMP, 16),
  (269, 2, 'PAC', 'PACHALUN', CURRENT_TIMESTAMP, 16),
  (270, 2, 'PLG', 'PLAYA GRANDE', CURRENT_TIMESTAMP, 16);

-- Municipios de Escuintla
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (271, 2, 'ESC', 'ESCUINTLA', CURRENT_TIMESTAMP, 17),
  (272, 2, 'SLC', 'SANTA LUCIA COTZUMALGUAPA', CURRENT_TIMESTAMP, 17),
  (273, 2, 'LAD', 'LA DEMOCRACIA', CURRENT_TIMESTAMP, 17),
  (274, 2, 'SIQ', 'SIQUINALA', CURRENT_TIMESTAMP, 17),
  (275, 2, 'MAG', 'MASAGUA', CURRENT_TIMESTAMP, 17),
  (276, 2, 'TIQ', 'TIQUISATE', CURRENT_TIMESTAMP, 17),
  (277, 2, 'GOM', 'LA GOMERA', CURRENT_TIMESTAMP, 17),
  (278, 2, 'GUA', 'GUANAGAZAPA', CURRENT_TIMESTAMP, 17),
  (279, 2, 'SJO', 'SAN JOSE', CURRENT_TIMESTAMP, 17),
  (280, 2, 'IZT', 'IZTAPA', CURRENT_TIMESTAMP, 17),
  (281, 2, 'PAL', 'PALIN', CURRENT_TIMESTAMP, 17),
  (282, 2, 'SVP', 'SAN VICENTE PACAYA', CURRENT_TIMESTAMP, 17),
  (283, 2, 'NCC', 'NUEVA CONCEPCION', CURRENT_TIMESTAMP, 17);

-- Municipios de Guatemala
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (284, 2, 'GUA', 'GUATEMALA', CURRENT_TIMESTAMP, 18),
  (285, 2, 'SCP', 'SANTA CATARINA PINULA', CURRENT_TIMESTAMP, 18),
  (286, 2, 'SJP', 'SAN JOSE PINULA', CURRENT_TIMESTAMP, 18),
  (287, 2, 'SJG', 'SAN JOSE DEL GOLFO', CURRENT_TIMESTAMP, 18),
  (288, 2, 'PAL', 'PALENCIA', CURRENT_TIMESTAMP, 18),
  (289, 2, 'CHN', 'CHINAUTLA', CURRENT_TIMESTAMP, 18),
  (290, 2, 'SPA', 'SAN PEDRO AYAMPUC', CURRENT_TIMESTAMP, 18),
  (291, 2, 'MIX', 'MIXCO', CURRENT_TIMESTAMP, 18),
  (292, 2, 'SPS', 'SAN PEDRO SACATEPEQUEZ', CURRENT_TIMESTAMP, 18),
  (293, 2, 'SJS', 'SAN JUAN SACATEPEQUEZ', CURRENT_TIMESTAMP, 18),
  (294, 2, 'SRA', 'SAN RAYMUNDO', CURRENT_TIMESTAMP, 18),
  (295, 2, 'CHR', 'CHUARRANCHO', CURRENT_TIMESTAMP, 18),
  (296, 2, 'FRA', 'FRAIJANES', CURRENT_TIMESTAMP, 18),
  (297, 2, 'AMA', 'AMATITLAN', CURRENT_TIMESTAMP, 18),
  (298, 2, 'VIN', 'VILLA NUEVA', CURRENT_TIMESTAMP, 18),
  (299, 2, 'VCA', 'VILLA CANALES', CURRENT_TIMESTAMP, 18),
  (300, 2, 'SMP', 'SAN MIGUEL PETAPA', CURRENT_TIMESTAMP, 18);

-- Municipios de Sacatepequez
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (301, 2, 'ANT', 'ANTIGUA', CURRENT_TIMESTAMP, 19),
  (302, 2, 'JOC', 'JOCOTENANGO', CURRENT_TIMESTAMP, 19),
  (303, 2, 'PAS', 'PASTORES', CURRENT_TIMESTAMP, 19),
  (304, 2, 'SUM', 'SUMPANGO', CURRENT_TIMESTAMP, 19),
  (305, 2, 'XEN', 'SANTO DOMINGO XENACOJ', CURRENT_TIMESTAMP, 19),
  (306, 2, 'SAS', 'SANTIAGO SACATEPEQUEZ', CURRENT_TIMESTAMP, 19),
  (307, 2, 'SBA', 'SAN BARTOLOME MILPAS ALTAS', CURRENT_TIMESTAMP, 19),
  (308, 2, 'SLU', 'SAN LUCAS SACATEPEQUEZ', CURRENT_TIMESTAMP, 19),
  (309, 2, 'SMI', 'SANTA LUCIA MILPAS ALTAS', CURRENT_TIMESTAMP, 19),
  (310, 2, 'MAG', 'MAGDALENA MILPAS ALTAS', CURRENT_TIMESTAMP, 19),
  (311, 2, 'SMJ', 'SANTA MARIA DE JESUS', CURRENT_TIMESTAMP, 19),
  (312, 2, 'CVI', 'CIUDAD VIEJA', CURRENT_TIMESTAMP, 19),
  (313, 2, 'SDU', 'SAN MIGUEL DUENAS', CURRENT_TIMESTAMP, 19),
  (314, 2, 'ALO', 'ALOTENANGO', CURRENT_TIMESTAMP, 19),
  (315, 2, 'SAA', 'SAN ANTONIO AGUAS CALIENTES', CURRENT_TIMESTAMP, 19),
  (316, 2, 'SCB', 'SANTA CATARINA BARAHONA', CURRENT_TIMESTAMP, 19);

-- Municipios de Totonicapán
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (317, 2, 'TOT', 'TOTONICAPAN', CURRENT_TIMESTAMP, 20),
  (318, 2, 'SCT', 'SAN CRISTOBAL TOTONICAPAN', CURRENT_TIMESTAMP, 20),
  (319, 2, 'SFA', 'SAN FRANCISCO EL ALTO', CURRENT_TIMESTAMP, 20),
  (320, 2, 'SAX', 'SAN ANDRES XECUL', CURRENT_TIMESTAMP, 20),
  (321, 2, 'MOM', 'MOMOSTENANGO', CURRENT_TIMESTAMP, 20),
  (322, 2, 'SMC', 'SANTA MARIA CHIQUIMULA', CURRENT_TIMESTAMP, 20),
  (323, 2, 'SLR', 'SANTA LUCIA LA REFORMA', CURRENT_TIMESTAMP, 20),
  (324, 2, 'SBA', 'SAN BARTOLO AGUAS CALIENTES', CURRENT_TIMESTAMP, 20);
  
  -- Municipios de El Progreso
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (325, 2, 'GUA', 'GUASTATOYA', CURRENT_TIMESTAMP, 21),
  (326, 2, 'SCP', 'MORAZAN', CURRENT_TIMESTAMP, 21),
  (327, 2, 'SJP', 'SAN AGUSTIN ACASAGUASTLAN', CURRENT_TIMESTAMP, 21),
  (328, 2, 'SJG', 'SAN CRISTOBAL ACASAGUASTLAN', CURRENT_TIMESTAMP, 21),
  (329, 2, 'PAL', 'EL JICARO', CURRENT_TIMESTAMP, 21),
  (330, 2, 'CHN', 'SANSARE', CURRENT_TIMESTAMP, 21),
  (331, 2, 'SPA', 'SANARATE', CURRENT_TIMESTAMP, 21),
  (332, 2, 'MIX', 'SAN ANTONIO LA PAZ', CURRENT_TIMESTAMP, 21);

  
-- Municipios de Quetzaltenango
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion, departamento)
VALUES
  (333, 2, 'QUX', 'QUETZALTENANGO', CURRENT_TIMESTAMP, 22),
  (334, 2, 'SCQ', 'SALCAJA', CURRENT_TIMESTAMP, 22),
  (335, 2, 'OLN', 'OLINTEPEQUE', CURRENT_TIMESTAMP, 22),
  (336, 2, 'SCS', 'SAN CARLOS SIJA', CURRENT_TIMESTAMP, 22),
  (337, 2, 'SBL', 'SIBILIA', CURRENT_TIMESTAMP, 22),
  (338, 2, 'CAB', 'CABRICAN', CURRENT_TIMESTAMP, 22),
  (339, 2, 'CJO', 'CAJOLA', CURRENT_TIMESTAMP, 22),
  (340, 2, 'SMS', 'SAN MIGUEL SIGUILA', CURRENT_TIMESTAMP, 22),
  (341, 2, 'SJO', 'SAN JUAN OSTUNCALCO', CURRENT_TIMESTAMP, 22),
  (342, 2, 'SMT', 'SAN MATEO', CURRENT_TIMESTAMP, 22),
  (343, 2, 'CCH', 'CONCEPCION CHIQUIRICHAPA', CURRENT_TIMESTAMP, 22),
  (344, 2, 'SMS', 'SAN MARTIN SACATEPEQUEZ', CURRENT_TIMESTAMP, 22),
  (345, 2, 'ALM', 'ALMOLONGA', CURRENT_TIMESTAMP, 22),
  (346, 2, 'CNT', 'CANTEL', CURRENT_TIMESTAMP, 22),
  (347, 2, 'HUI', 'HUITAN', CURRENT_TIMESTAMP, 22),
  (348, 2, 'ZUN', 'ZUNIL', CURRENT_TIMESTAMP, 22),
  (349, 2, 'CCC', 'COLOMBA COSTA CUCA', CURRENT_TIMESTAMP, 22),
  (350, 2, 'SFL', 'SAN FRANCISCO LA UNION', CURRENT_TIMESTAMP, 22),
  (351, 2, 'PAL', 'EL PALMAR', CURRENT_TIMESTAMP, 22),
  (352, 2, 'CTP', 'COATEPEQUE', CURRENT_TIMESTAMP, 22),
  (353, 2, 'GCC', 'GENOVA COSTA CUCA', CURRENT_TIMESTAMP, 22),
  (354, 2, 'FCC', 'FLORES COSTA CUCA', CURRENT_TIMESTAMP, 22),
  (355, 2, 'LES', 'LA ESPERANZA', CURRENT_TIMESTAMP, 22),
  (356, 2, 'PLA', 'PALESTINA DE LOS ALTOS', CURRENT_TIMESTAMP, 22);


-- INSERT DE LOS TIPOS DE CANDIDATOS
INSERT INTO votaciones.Catalogo (idCatalogo, idTipoCatalogo, codigo, descripcion, fechaAdicion)
VALUES 
  (357, 3, 'PRE', 'Presidente', CURRENT_TIMESTAMP),
  (358, 3, 'VCP', 'Vicepresidente', CURRENT_TIMESTAMP),
  (359, 3, 'ALC', 'Alcalde', CURRENT_TIMESTAMP),
  (360, 3, 'DDP', 'Diputado Departamental', CURRENT_TIMESTAMP),
  (361, 3, 'DN', 'Diputado Nacional', CURRENT_TIMESTAMP);
